In [197]:
import os
import re
import random
import string
import numpy as np

In [198]:
import tensorflow as tf

In [199]:
!pip install numpy

In [200]:
!pip install --upgrade tensorflow

In [201]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers import TextVectorization

In [202]:
class TokenPositionEmbedding(layers.Layer):
    def __init__(self, maxlen, vocab_size, embed_size):
        super(TokenPositionEmbedding, self).__init__()
        
        self.token_embed = layers.Embedding(input_dim=vocab_size, output_dim=embed_dim) # input_dim = 20000 --> output_dim = 256
        self.position_embed = layers.Embedding(input_dim=maxlen, output_dim=embed_dim) # input_dim = 80 --> output_dim = 256
        
    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen) # [0, 1, 2, 3 ... maxlen]
        positions = self.position_embed(positions) # [0.343434, 0.594534, 1.53434, 0.786554... embed_dim]
        x = self.token_embed(x)
        
        return x + positions

In [203]:
class TransformerBlock(layers.Layer):
    def __init__(self, embed_dims, num_heads, learning_rate=0.15):
        super(TransformerBlock, self).__init__()
        
        self.attention = layers.MultiHeadAttention(num_heads, embed_dim)
        self.dropout1 = layers.Dropout(learning_rate)
        self.norm1 = layers.LayerNormalization(epsilon=1e-6)
        
        self.feed_forward_network = keras.Sequential([
            layers.Dense(embed_dims, activation='relu'),
            layers.Dense(embed_dims)
            
        ])
        
        self.dropout2 = layers.Dropout(learning_rate)
        self.norm2 = layers.LayerNormalization(epsilon=1e-6)
        
        
    def call(self, inputs):
        batch_size, seq_len = tf.shape(inputs)[0], tf.shape(inputs)[1] 

In [204]:
np_array_2d = np.arange(0, 6).reshape([2, 3])

In [205]:
np_array_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [206]:
np_array_2d_1 = np.arange(0, 6).reshape([3, 2])

In [207]:
np_array_2d_1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [208]:
result1 = np.sum(np_array_2d, axis=0)

In [209]:
result1

array([3, 5, 7])

In [210]:
result2 = np.sum(np_array_2d_1, axis=0)

In [211]:
result2

array([6, 9])

In [212]:
result3 = np.sum(np_array_2d, axis=1)

In [213]:
result3

array([ 3, 12])

In [214]:
np_array_1s = np.array([
  [1, 1, 1],
  [1, 1, 1]
])

In [215]:
np_array_9s = np.array([
    [9, 9, 9],
    [9, 9, 9]
])

In [216]:
np_array_9s

array([[9, 9, 9],
       [9, 9, 9]])

In [217]:
np_array_1s

array([[1, 1, 1],
       [1, 1, 1]])

In [218]:
concatenated_output = np.concatenate([np_array_1s, np_array_9s], axis = 0)

In [219]:
concatenated_output

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [220]:
concatenated_output_for_axis1 = np.concatenate([np_array_1s, np_array_9s], axis = 1)

In [221]:
concatenated_output_for_axis1

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [222]:
nparray_one_1dimensional = np.array([1, 1, 1])

In [223]:
nparray_nine_1dimensional = np.array([9, 9, 9])

In [224]:
nparray_one_1dimensional

array([1, 1, 1])

In [225]:
nparray_nine_1dimensional

array([9, 9, 9])

In [226]:
outtt = np.concatenate([nparray_one_1dimensional, nparray_nine_1dimensional])

In [227]:
outtt

array([1, 1, 1, 9, 9, 9])

In [228]:
c = []
a = [1, 2, 3, 4, 5, 6, 7]
b = [7, 6, 5, 4, 3, 2, 1]

In [229]:
for i in range(len(a)):
    c.append(a[i]*b[i])

In [230]:
c

[7, 12, 15, 16, 15, 12, 7]

In [231]:
np_array_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [232]:
np_array_2d.ndim

2

In [233]:
np_array_2d.shape

(2, 3)

In [234]:
np_array_2d.size

6

In [235]:
np_array_2d.dtype

dtype('int64')

In [236]:
np_array_2d.itemsize

8

In [237]:
np_array_2d.data

In [238]:
import numpy as np

In [239]:
a = np.arange(15).reshape(3, 5)

In [240]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [241]:
from numpy import pi
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [242]:
x = np.linspace(0, 2 * pi, 100)

In [243]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [244]:
x.size

100

In [245]:
c = np.arange(48).reshape(2, 6, 4)

In [246]:
d = np.arange(48).reshape(4, 6, 2)

In [247]:
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47]]])

In [248]:
A = np.array([
        [1, 2], [0, 3]])

In [249]:
B = np.array([
    [4, 5], [7, 9]])

In [250]:
A

array([[1, 2],
       [0, 3]])

In [251]:
B

array([[4, 5],
       [7, 9]])

In [252]:
A * B

array([[ 4, 10],
       [ 0, 27]])

In [253]:
A @ B

array([[18, 23],
       [21, 27]])

In [254]:
rg = np.random.default_rng(1)

In [255]:
b = np.linspace(0, pi, 3)

In [256]:
b

array([0.        , 1.57079633, 3.14159265])

In [257]:
b = np.arange(12).reshape(3, 4)

In [258]:
B.sum(axis=0)

array([11, 14])

In [259]:
B.sum(axis=1)

array([ 9, 16])

In [260]:
B.min(axis=0)

array([4, 5])

In [261]:
B.cumsum(axis=1)

array([[ 4,  9],
       [ 7, 16]])

In [262]:
F = np.arange(3)

In [263]:
F

array([0, 1, 2])

In [264]:
np.exp(F)

array([1.        , 2.71828183, 7.3890561 ])

In [265]:
a = np.arange(10)**3

In [266]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [267]:
a[2]

8

In [268]:
a[2:7]

array([  8,  27,  64, 125, 216])

In [269]:
ehzaArr = np.arange(20)**3

In [270]:
ehzaArr

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859])

In [271]:
ehzaArr

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859])

In [272]:
ehzaArr[3: 7]

array([ 27,  64, 125, 216])

In [273]:
ehzaArr[0: 8: 2] = 100

In [274]:
ehzaArr

array([ 100,    1,  100,   27,  100,  125,  100,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859])

In [275]:
ehzaArr

array([ 100,    1,  100,   27,  100,  125,  100,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859])

In [276]:
ehzaArr[::-1]

array([6859, 5832, 4913, 4096, 3375, 2744, 2197, 1728, 1331, 1000,  729,
        512,  343,  100,  125,  100,   27,  100,    1,  100])

In [277]:
ehzaArr[::]

array([ 100,    1,  100,   27,  100,  125,  100,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859])

In [278]:
for i in a:
    print(i**(1/3))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [279]:
def f(x, y):
    return 10 * x + y

In [280]:
f

<function __main__.f(x, y)>

In [281]:
b = np.fromfunction(f, (5, 4), dtype=int)

In [282]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [283]:
def odd(x, y):
    return x + y

In [284]:
hahah = np.fromfunction(odd, (3, 3), dtype=int)

In [285]:
hahah

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [286]:
hahah[0:3, 1]

array([1, 2, 3])

In [287]:
hahah[0:3, 1:2]

array([[1],
       [2],
       [3]])

In [288]:
hahah[0:3, :]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [289]:
hahah[:, :]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [290]:
hahah[-1]

array([2, 3, 4])

In [291]:
c = np.array([
    [
      [0, 1, 2],
      [10, 12, 13]
    ],
    [
      [100, 101, 102],
      [110, 112, 113]
    ]
])

In [292]:
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [293]:
c[0, ...]

array([[ 0,  1,  2],
       [10, 12, 13]])

In [294]:
# It covers all the axes
c[..., 1]

array([[  1,  12],
       [101, 112]])

In [295]:
c[..., 0]

array([[  0,  10],
       [100, 110]])

In [296]:
c[..., 2]

array([[  2,  13],
       [102, 113]])

In [297]:
for row in c:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


In [298]:
for outer in c:
    for innerRow in outer:
        for everyFirstEle in innerRow:
            print(everyFirstEle)

0
1
2
10
12
13
100
101
102
110
112
113


In [299]:
a = np.floor(20* rg.random((3, 4)))

In [300]:
a

array([[10., 19.,  2., 18.],
       [ 6.,  8., 16.,  8.],
       [10.,  0., 15., 10.]])

In [301]:
a.shape

(3, 4)

In [302]:
a.ravel()

array([10., 19.,  2., 18.,  6.,  8., 16.,  8., 10.,  0., 15., 10.])

In [303]:
a.reshape(4, -1)

array([[10., 19.,  2.],
       [18.,  6.,  8.],
       [16.,  8., 10.],
       [ 0., 15., 10.]])

In [304]:
a = np.floor(10 * rg.random((2, 2)))

In [305]:
a

array([[3., 7.],
       [3., 4.]])

In [306]:
b = np.floor(20 * rg.random((2, 2)))

In [307]:
b

array([[2., 8.],
       [4., 5.]])

In [308]:
np.vstack((a, b))

array([[3., 7.],
       [3., 4.],
       [2., 8.],
       [4., 5.]])

In [309]:
np.vstack((a, b)).shape

(4, 2)

In [310]:
np.hstack((a, b)).shape

(2, 4)

In [311]:
from numpy import newaxis

In [312]:
np.column_stack((a, b))

array([[3., 7., 2., 8.],
       [3., 4., 4., 5.]])

In [313]:
m = np.array([7., 9.])

In [314]:
n = np.array([3., 8.])

In [315]:
m

array([7., 9.])

In [316]:
m.shape

(2,)

In [317]:
n.shape

(2,)

In [318]:
np.column_stack((m, n)).shape

(2, 2)

In [319]:
m.shape + n.shape

(2, 2)

In [320]:
type(m.shape)

tuple

In [321]:
n.shape

(2,)

In [322]:
m

array([7., 9.])

In [323]:
n

array([3., 8.])

In [324]:
a = np.arange(12)**2

In [325]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [326]:
i = np.array([1, 1, 3, 8, 10])


In [327]:
a[i]

array([  1,   1,   9,  64, 100])

In [328]:
data = np.array([1.0, 2.0])

In [329]:
data

array([1., 2.])

In [330]:
data * 1.6

array([1.6, 3.2])

In [331]:
amaderData = np.array([
    [1, 2],
    [33, 44],
    [5, 6]
])

In [332]:
amaderData

array([[ 1,  2],
       [33, 44],
       [ 5,  6]])

In [333]:
import pandas as pd

In [334]:
x = pd.read_csv('music.csv', header=0)

In [335]:
type(x)

pandas.core.frame.DataFrame

In [336]:
y = pd.read_csv('music.csv', usecols=['Genre', 'Artist'])

In [337]:
y

Artist  Genre
0  Billie Holiday   Jazz
1    Jimi Hendrix   Rock
2     Miles Davis  Indie
3             SIA    Pop
4   Billie Eilish    Pop

In [338]:
amarDataFrame = pd.DataFrame(x)

In [339]:
amarDataFrame

Artist  Genre  Listeners  Plays
0  Billie Holiday   Jazz    2700000  34000
1    Jimi Hendrix   Rock     120000  70222
2     Miles Davis  Indie       3000  48000
3             SIA    Pop       1999  74000
4   Billie Eilish    Pop      20000  98990

In [340]:
amarDataFrame.to_csv('musicdataFrame.csv')

In [341]:
type(amarDataFrame)

pandas.core.frame.DataFrame

In [342]:
import os
import re
import random
import string
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers import TextVectorization

In [381]:
# Embedding
from numpy import array

docs = [
    'Well done!', #1
    'Good work', #1
    'Great effort', #1
    'nice work', #1
    'Excellent', #1
    'Weak', #0
    'Poor Effort', #0
    'not good', #0
    'Poor work man', #0
    'Could have done better' #0
]

In [382]:
labels = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [383]:
labels

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [384]:
vocab_size = 50

In [385]:
encoded_docs = [ tf.keras.preprocessing.text.one_hot(d, vocab_size) for d in docs ]

In [386]:
encoded_docs

[[1, 35],
 [18, 42],
 [25, 46],
 [44, 42],
 [14],
 [17],
 [33, 46],
 [9, 18],
 [33, 42, 42],
 [17, 30, 35, 47]]

In [387]:
# Pad documents to a max length of four words
max_length = 4

# padded_docs = tf.keras.preprocessing.sequence.pad_sequences(encoded_docs, maxlen=max_length, padding='pre')
padded_docs = tf.keras.preprocessing.sequence.pad_sequences(encoded_docs, maxlen=max_length, padding='post')

In [388]:
padded_docs

array([[ 1, 35,  0,  0],
       [18, 42,  0,  0],
       [25, 46,  0,  0],
       [44, 42,  0,  0],
       [14,  0,  0,  0],
       [17,  0,  0,  0],
       [33, 46,  0,  0],
       [ 9, 18,  0,  0],
       [33, 42, 42,  0],
       [17, 30, 35, 47]], dtype=int32)

In [389]:
# Define the model
model = tf.keras.Sequential()
model.add(layers.Embedding(vocab_size, 8, input_length=max_length))
model.add(layers.Flatten())
model.add(layers.Dense(1, activation='sigmoid'))

In [390]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [391]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten_2 (Flatten)         (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________


In [404]:
model.fit(padded_docs, labels, epochs=50, verbose=0)

In [405]:
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)

In [406]:
loss

0.2408333718776703

In [407]:
accuracy

1.0